2024-03 | TT-Buda Release Alignment
2024-03 | TT-Buda Release Alignment 

---------

Co-authored-by: Milan Kordic <mkordic@tenstorrent.com>
Co-authored-by: anirudTT <aramchandran@tenstorrent.com>

diff --git a/run_benchmark_tt_perf b/run_benchmark_tt_perf
--- a/run_benchmark_tt_perf
+++ b/run_benchmark_tt_perf
@@ -13,7 +13,14 @@ TT_DEVICE=$1
 echo "Running TT-Model Benchmarking on $TT_DEVICE"
 
 # BERT - Text Classification - SST-2
-python benchmark.py -d tt -m bert -c large --task text_classification -mb 64 --loop_count 4 --save_output
+if [ "$TT_DEVICE" = "wormhole" ]; then
+    python benchmark.py -d tt -m bert -c large --task text_classification -mb 64 -df Bfp8_b -mf LoFi --loop_count 4 --save_output
+elif [ "$TT_DEVICE" = "grayskull" ]; then
+    python benchmark.py -d tt -m bert -c large --task text_classification -mb 64 --loop_count 4 --save_output
+else
+    echo "Invalid TT_DEVICE: $TT_DEVICE"
+    exit 1
+fi
 
 # ResNet - Image Classification - ImageNet
 python benchmark.py -d tt -m resnet -c resnet50 --task image_classification -mb 64 --loop_count 8 --save_output
@@ -89,7 +96,7 @@ python benchmark.py -d tt -m yolo_v5 -c s --task object_detection -mb 64 --loop_
 python benchmark.py -d tt -m open_pose -c 2d --task pose_estimation -mb 64 -df Fp16 --loop_count 4 --save_output
 
 # U-Net - Segmentation - Brain LGG Dataset
-python benchmark.py -d tt -m unet -c 256 --task segmentation -mb 48 --loop_count 1 --save_output
+python benchmark.py -d tt -m unet -c 256 --task segmentation -mb 48 --loop_count 32 --save_output
 
 # Inception-v4 - Image Classification - ImageNet
 python benchmark.py -d tt -m inception_v4 -c 224 --task image_classification -mb 64 --loop_count 8 --save_output
