Update BERT Wormhole perf run command

diff --git a/run_benchmark_tt_perf b/run_benchmark_tt_perf
--- a/run_benchmark_tt_perf
+++ b/run_benchmark_tt_perf
@@ -13,7 +13,14 @@ TT_DEVICE=$1
 echo "Running TT-Model Benchmarking on $TT_DEVICE"
 
 # BERT - Text Classification - SST-2
-python benchmark.py -d tt -m bert -c large --task text_classification -mb 64 --loop_count 4 --save_output
+if [ "$TT_DEVICE" = "wormhole" ]; then
+    python benchmark.py -d tt -m bert -c large --task text_classification -mb 64 -df Bfp8_b -mf LoFi --loop_count 4 --save_output
+elif [ "$TT_DEVICE" = "grayskull" ]; then
+    python benchmark.py -d tt -m bert -c large --task text_classification -mb 64 --loop_count 4 --save_output
+else
+    echo "Invalid TT_DEVICE: $TT_DEVICE"
+    exit 1
+fi
 
 # ResNet - Image Classification - ImageNet
 python benchmark.py -d tt -m resnet -c resnet50 --task image_classification -mb 64 --loop_count 8 --save_output
